site_name: Cisco Live 2022 WILCLD-2611
site_description: Welcome to the 'Containerized Applications on Hybrid Cloud Environments' Lab.

nav:
  - Home: index.md
  - Lab Access:
    - Accessing the Lab Environment: LAB_access.md
  - Cisco Container Platform:
    - Explore Cisco Container Platform (CCP): ccp_exploring.md
    - Create ON-PREM Tenant Cluster: ccp_create_cluster-onprem.md
    - Create AWS Tenant Cluster: ccp_create_cluster-aws.md
    - Connect Cluster in AWS to Hybrid Network: ccp_connect_eks_to_hybrid_network.md
    - Access Tenant Cluster: ccp_accessing_kubernetes_cluster.md
  - Hybrid Cloud IoT Application:
    - Deploy Backend App on Tenant Clusters: deploy_backend.md
    - Deploy Frontend App on Amazon Cloud: deploy_frontend-aws.md
  - Appendixes:
    - Explore Backend Application: backend_exercise.md
    - Kubernetes Network Policies:
      - Apply Security Policy to REST API Agent: security_policies.md
    - Guacamole: guacamole.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences