site_name: Cisco Live 2022 WILCLD-2611
site_description: Welcome to the 'Containerized Applications on Hybrid Cloud Environments' Lab.

nav:
  - Home: index.md
  - Lab Access: LAB_access-RDP.md
  - Hybrid Cloud IoT Application:
    - Deploy Backend App on Tenant Clusters: deploy_backend.md
    - Deploy Frontend App on Amazon Cloud: deploy_frontend-aws.md
  - Explore Intersight: intersight.md
  - Appendixes:
    - Explore Backend Application: backend_exercise.md
    - Kubernetes Network Policies:
      - Apply Security Policy to REST API Agent: security_policies.md
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.superfences