---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-backend-mqtt-db-agent
  labels:
    app: iot-backend
    tier: mqtt-db-agent
spec:
  selector:
    matchLabels:
      app: iot-backend-mqtt-db-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iot-backend-mqtt-db-agent
    spec:
      containers:
      - image: eu.gcr.io/fwardz001-poc-ci1s/mqtt_db_plugin:v9
        name: mqtt-db-agent
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-root-pass
              key: password
