---
apiVersion: v1
kind: Namespace
metadata:
  name: student17
spec:
  finalizers:
  - kubernetes
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: student17
  name: student17-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: student17-binding
  namespace: student17
subjects:
  - kind: Group
    name: student17-group
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: student17-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-list
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-list
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: student17-group