---
apiVersion: v1
kind: Service
metadata:
  name: frontend-iot-service
  labels:
    app: iot-frontend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: iot-frontend
  type: "LoadBalancer"